export const ENEMY_TYPE = 'ENEMY_TYPE';
export const SPEED_ITEM_TYPE = 'SPEED_ITEM_TYPE';
export const DESTROY_ALL_ITEM_TYPE = 'DESTROY_ALL_ITEM_TYPE';
export const FROZEN_ITEM_TYPE = 'FROZEN_ITEM_TYPE';
